name: Munki Deploy (AWS S3 + CloudFront)

on:
  push:
    branches: [main]
    paths:   ['deployment/**']

jobs:
  deploy:
    runs-on: macos-13
    env:
      S3_BUCKET:  ${{ secrets.S3_BUCKET }}
      DIST_ID:    ${{ secrets.CLOUDFRONT_DIST }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          deployment
          pipelines
        fetch-depth: 1

    - name: Configure AWS creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.AWS_REGION }}

    - name: Install Munki + deps
      run: |
        brew install munki

    - name: Build catalogs
      run: |
        /usr/local/munki/makecatalogs --skip-pkg-check "${{ github.workspace }}/deployment"

    - name: Clean temp chunks
      run: |
        find deployment/pkgs -type f \( -name '*.pkg.*' -o -name '*.dmg.*' \) -delete

    - name: Sync catalogs to S3
      run: |
        aws s3 sync deployment/catalogs  s3://$S3_BUCKET/repo/deployment/catalogs  --delete

    - name: Sync manifests + pkgsinfo
      run: |
        aws s3 sync deployment/manifests s3://$S3_BUCKET/repo/deployment/manifests --delete
        aws s3 sync deployment/pkgsinfo  s3://$S3_BUCKET/repo/deployment/pkgsinfo  --delete

    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/*"
